import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import SessionWrapper from "@/components/auth/SessionWrapper";
import ErrorAlert from "@/components/auth/ErrorAlert";
import Nav from "@/components/Nav";
import { ThemeProvider } from "@/context/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <Nav />
          <ErrorAlert />
          <SessionWrapper>
            <div className="pt-[8vh]">
              {children}
            </div>
          </SessionWrapper>
        </ThemeProvider>

      </body>
    </html>
  );
}
